name: crud_angular
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  angular: ^5.3.1
  essential_rest: ^1.0.18
  angular_forms: any

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: any
  pedantic: ^1.9.0
  test: ^1.6.3
